# Generated by Django 2.1.7 on 2019-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
