# Generated by Django 2.1.7 on 2019-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activation_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='m1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activation',
            name='m2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activation',
            name='m3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activation',
            name='m4',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
