# Generated by Django 2.1.7 on 2019-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190415_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
